import Head from "next/head";
import Image from "next/image";
import Header from "@/components/Header/Header";
import Content from "@/components/Content/Content";
import Footer from "@/components/Footer/Footer";

const Home = () => {
  return (
    <>
      <Head>
        <title>Wealth Chimp</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div id="app">
        <Header />
        <Content />
        <Footer />
      </div>
    </>
  );
};

export default Home;
